// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using JorgeGuillen.Alumno.service.Domain.College.Entities;
using JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts.Configurations
{
    public partial class AlumnoConfiguration : IEntityTypeConfiguration<Alumno>
    {
        public void Configure(EntityTypeBuilder<Alumno> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Alumno__3214EC0797745E7A");

            entity.ToTable("Alumno");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Apellido)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Dni).HasColumnName("DNI");
            entity.Property(e => e.Nombre)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alumno> entity);
    }
}
