// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using JorgeGuillen.Alumno.service.Domain.College.Entities;
using JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts.Configurations
{
    public partial class CursoConfiguration : IEntityTypeConfiguration<Curso>
    {
        public void Configure(EntityTypeBuilder<Curso> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Curso__3214EC07E9B7C0F9");

            entity.ToTable("Curso");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.DescripcionCurso).IsRequired();
            entity.Property(e => e.NombreCurso)
            .IsRequired()
            .HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Curso> entity);
    }
}
