// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using JorgeGuillen.Alumno.service.Domain.College.Entities;
using JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts.Configurations
{
    public partial class InscripcionConfiguration : IEntityTypeConfiguration<Inscripcion>
    {
        public void Configure(EntityTypeBuilder<Inscripcion> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Inscripc__3214EC0766137AFF");

            entity.ToTable("Inscripcion");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Docente).IsRequired();

            entity.HasOne(d => d.Alumno).WithMany(p => p.Inscripcions)
            .HasForeignKey(d => d.AlumnoId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Inscripcion_Alumno");

            entity.HasOne(d => d.Curso).WithMany(p => p.Inscripcions)
            .HasForeignKey(d => d.CursoId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Inscripcion_Curso");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Inscripcion> entity);
    }
}
