// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Domain.College.Entities;

public partial class Alumno
{
    public Guid Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int Dni { get; set; }

    public virtual ICollection<Inscripcion> Inscripcions { get; set; } = new List<Inscripcion>();
}