// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Domain.College.Entities;

public partial class Curso
{
    public Guid Id { get; set; }

    public string NombreCurso { get; set; }

    public double HorasCurso { get; set; }

    public string DescripcionCurso { get; set; }

    public virtual ICollection<Inscripcion> Inscripcions { get; set; } = new List<Inscripcion>();
}