// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JorgeGuillen.Alumno.service.Domain.College.Entities;

public partial class Inscripcion
{
    public Guid Id { get; set; }

    public Guid AlumnoId { get; set; }

    public Guid CursoId { get; set; }

    public string Docente { get; set; }

    public virtual Alumno Alumno { get; set; }

    public virtual Curso Curso { get; set; }
}