// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using JorgeGuillen.Alumno.service.Domain.College.Entities;
using JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace JorgeGuillen.Alumno.service.Infraestructure.Persistence.Contexts;

public partial class CollegeDBContext : DbContext
{
    public CollegeDBContext(DbContextOptions<CollegeDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alumno> Alumnos { get; set; }

    public virtual DbSet<Curso> Cursos { get; set; }

    public virtual DbSet<Inscripcion> Inscripcions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.AlumnoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CursoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InscripcionConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
